### ISSUE TITLE
运行到模拟器里短篇和连载没内容

### ISSUE THREAD

**Issue by JaynChen** [meilbn/MyOne3-iOS#3]
运行到模拟器里，文章和连载内容确实为空，我更换了几个模拟器都是一样的情况，在其他电脑上的模拟器运行也是一样为空的情况。但是我运行到真机，那些内容又都是正常的。

**Comment by meilbn** [comment]
好的，我晚上测测看。

**Comment by meilbn** [comment]
我在模拟器上运行了下，的确是没有显示出内容文字，但是我用 Reveal 查看了下视图，YYTextView 是有文字的，估计是在模拟器上没渲染出来，如果真机没有这个问题，那也不碍事。。。
而且高度也是计算正确的，只是没渲染出来。。。

**Comment by JaynChen** [comment]
现在才注意到各文件的命名所代表类型的规律，末尾有controller的类都是控制器，负责逻辑处理和交互，末尾有view和cell的类是视图，负责显示，除此之外的绝大部份类都是模型（Network和ToolKit文件夹下的类是公共的工具类），负责存取数据。我觉得在所有模型类后缀名都加上一个model来标识应该会更好阅读，你是怎么考虑的？

**Comment by meilbn** [comment]
其实看文件夹的名字就看得出来的。。。
View、VC 都有后缀了，Model 就不用加了，这是我的看法，加上去有点多余，不过你可以按照你的想法来，并没有绝对的规范吧。。。

**Comment by JaynChen** [comment]
因为你还有Vendors文件夹下的第三方内容，里面的文件后缀既没有View，也没有VC，所以排除法辨认model不怎么准确。加上model可以让代码阅读更流畅，不用跳转过去看。

**Comment by JaynChen** [comment]
今天运行代码测试我发现今天的短篇在模拟器有显示出来，可滑到前几天的又没有。于是我猜测这个问题和contentView的高度有关，于是将字体从15改到5，短篇和连载里的内容就都出来了，就是字特别小，看不清。你有什么思路么？

**Comment by meilbn** [comment]
用的是 YYTextView，应该跟渲染有关。。。
有时候模拟器上分割线滑动的时候都时而出现时而不出现的。。。
