### ISSUE TITLE
阅读界面下轮播图里的Top10图片显示有问题

### ISSUE THREAD

**Issue by JaynChen** [meilbn/MyOne3-iOS#4]
点击进入Top10后缓慢上滑，滑到图片时可看到图片变虚化了，然后到底后图片突然从虚化变为清晰正常，之后就都正常了。

**Comment by meilbn** [comment]
yup。。。
这个效果没实现好。。。
后面会改下的。。。

**Comment by meilbn** [comment]
@JaynChen 已经改了，不过感觉还不是很完美，跟官方的还是有一小点差别。

**Comment by meilbn** [comment]
38338379975019a6369b50934032205de4802237
这个 commit 里面修改了图片的缩放方式
