### ISSUE TITLE
请教一个问题，怎么抽取一个app的资源

### ISSUE THREAD

**Issue by huiyumiao** [meilbn/MyOne3-iOS#6]

**Comment by meilbn** [comment]
如果有 ipa 的话，应该简单点，可以直接解包，里面应该会有资源包，不过我没试过这种抽资源的，我都是直接从手机里面抽出来，可以参考我这篇博客：http://meilbn.com/2015/08/19/iosre-find-app-installation-and-sandbox-directory/
