### ISSUE TITLE
分享按钮的点击事件

### ISSUE THREAD

**Issue by TimorYang** [meilbn/MyOne3-iOS#7]
向您请教一个问题
您在scrollView中添加了3个透明的button,我有两个问题,第一个,ScrollView是可以滑动的,这三个按钮是会跟在后面滚动的,第二个问题就是,这三个button的事件会被内容View给拦截,看了您的代码,可是还是不知道该如何处理事件的传递.

**Comment by meilbn** [comment]
点击事件没有被拦截呀。。。
这三个按钮是透明的，是为了响应最后面那三个不动的有图标的按钮。。。
